# -*- coding: utf-8 -*-
"""batch_normalization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gf4JnOH22AE3uywjIoWRkm4LKJgTLkrX

Almost every convolutional layer in YOLO has batch normalization after it. It helps the model train faster and reduces variance between units.
"""

import tensorflow as tf

class BatchNormalization(tf.keras.layers.BatchNormalization):
# The layer will normalize its inputs using the mean and variance of its moving statistics, learned during training.
    def call(self, x, training=False):

        if training is None:
            training = tf.constant(False)
        training = tf.logical_and(training, self.trainable)

        return super().call(x, training)